// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Enterwell.VS.Links
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidLinksPackageString = "b167f3dc-c0da-43f0-99df-6d49c801f4cf";
        public static Guid guidLinksPackage = new Guid(guidLinksPackageString);

        public const string guidLinksPackageCmdSetString = "89548147-380c-45d9-845b-d481a7b391ce";
        public static Guid guidLinksPackageCmdSet = new Guid(guidLinksPackageCmdSetString);

        public const string enterwellLogoString = "1754edaa-bfa0-4c63-ae0c-575512c3e25b";
        public static Guid enterwellLogo = new Guid(enterwellLogoString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolbarGroup = 0x1000;
        public const int MenuController = 0x1020;
        public const int MenuControllerEssentialGroup = 0x1040;
        public const int MenuControllerAdditionalGroup = 0x1060;
        public const int AnchorCommandId = 0x0100;
        public const int WikiCommandId = 0x0105;
        public const int AzureCommandId = 0x0110;
        public const int ClockifyCommandId = 0x0115;
        public const int PlaceholderCommandId = 0x0120;
        public const int enterwellToolbarIcon = 0x0001;
    }
}